#!/usr/bin/env python3
"""Write _data/asset_digests.yml, the content fingerprints the templates append
to the URLs of style.css and the scripts.

The HTML and those files are cached independently, so without a fingerprint a
browser can pair new markup with the previous stylesheet until max-age expires
and render a broken page. A digest changes only when the file does, so an
unchanged asset keeps whatever the visitor already has.

Generated rather than computed in a Jekyll plugin: the github-pages gem forces
safe mode and a random plugins_dir, so _plugins is never loaded, here or in CI.
Run this before a local build too, or the templates render an empty stamp.

    python3 scripts/gen-asset-digests.py
"""

import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
OUT = os.path.join(ROOT, "_data", "asset_digests.yml")

# Every asset the markup loads with a versionless URL. Keep in step with the
# templates: an entry here that nothing references is dead weight, and an asset
# that is loaded without an entry goes back to the stale-cache problem.
ASSETS = [
    "style.css",
    "fonts/fonts.css",
    "js/lucide.min.js",
    "js/lottie.min.js",
    "js/marked.min.js",
]

DIGEST_CHARS = 12


def digest(path):
    with open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()[:DIGEST_CHARS]


def main():
    lines = ["# Generated by scripts/gen-asset-digests.py. Do not edit."]
    missing = []
    for rel in ASSETS:
        path = os.path.join(ROOT, rel)
        if not os.path.isfile(path):
            missing.append(rel)
            continue
        lines.append('"%s": "%s"' % (rel, digest(path)))

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    print("%s: %d digests" % (os.path.relpath(OUT, ROOT), len(lines) - 1))
    for rel in missing:
        print("warning: %s is listed but missing; it will ship unstamped" % rel, file=sys.stderr)


if __name__ == "__main__":
    main()